updated readme
kineticdata/peripherals-zoom pull request #1
Opened 2020-11-16 12:46 UTC by ChadRehmKineticData

The initial commit populated the master branch without a code review.  Could we get a full code review on the zoom api handler.  That is the only component in the repo at this time.

2020-11-16 15:58 UTC, jackboespflug requested changes
The description in the node.xml file indicates this is a generic Rest handler, when it should be updated to reflect it is a Zoom API handler.

Update that and the other two items I commented on, and it will be good to go.

2020-11-16 15:58 UTC, jackboespflug commented on handlers/zoom_api_v1/readme.md
>    HTTP Method to use for the Kinetic Core API call being made.
This references the Kinetic Core API - should be changed to the Zoom API.

2020-11-16 15:58 UTC, jackboespflug commented on handlers/zoom_api_v1/readme.md
> +**Path** :The relative API path (to the `https://api.zoom.us/v2` info value) that will be called. This value should begin with a forward slash `/`.  A list of [zoom](https://marketplace.zoom.us/docs/
You reference "info value" here, but it appears the **Path** parameter is always relative to 'https://api.zoom.us/v2'.

2020-11-17 17:37 UTC, ChadRehmKineticData commented
@jackboespflug I made the requested changes.

2020-11-17 19:15 UTC, jackboespflug approved these changes
Looks good.

2020-11-17 19:27 UTC, merged